name: marina_hotel_mobile
description: Marina Hotel Mobile App

version: 1.0.0+1

environment:
  sdk: '>=3.35.5 <4.0.0'
  flutter: '>=3.35.5'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  # Offline support
  sqflite: ^2.3.0
  connectivity_plus: ^5.0.1
  uuid: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  # Background sync
  workmanager: ^0.5.1
  # Local notifications
  flutter_local_notifications: ^16.1.0
  # JSON serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
