name: APK Build Simple

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'

    - name: Get Dependencies
      working-directory: ./mobile
      run: flutter pub get

    - name: Build APK
      working-directory: ./mobile
      run: |
        if [ "${{ github.event.inputs.build_type }}" = "release" ]; then
          flutter build apk --release
        else
          flutter build apk --debug
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: marina-hotel-apk
        path: mobile/build/app/outputs/flutter-apk/*.apk

    - name: Summary
      run: |
        echo "## 📱 APK Build Complete" >> $GITHUB_STEP_SUMMARY
        echo "- Build Type: ${{ github.event.inputs.build_type || 'debug' }}" >> $GITHUB_STEP_SUMMARY
        echo "- APK ready for download in Artifacts" >> $GITHUB_STEP_SUMMARY