name: Simple Marina Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Grant Permission
        run: chmod +x app-marina/gradlew
        
      - name: Build Debug APK
        run: |
          cd app-marina
          ./gradlew :app:assembleDebug --stacktrace --no-daemon
          
      - name: List APKs
        run: find app-marina -name "*.apk" -type f
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: marina-apk
          path: app-marina/app/build/outputs/apk/debug/app-debug.apk