name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Simple Test
      run: |
        echo "✅ Workflow is working!"
        echo "🚀 GitHub Actions are functioning properly"